# Generated by Django 4.0.6 on 2022-08-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_buyukcard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyukCard',
            new_name='BuyukCardCocuk',
        ),
    ]
