# Generated by Django 4.0.6 on 2022-08-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_footer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Yanresim',
            new_name='YanresimCocuk',
        ),
    ]
