# Generated by Django 4.0.6 on 2022-08-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_rename_yanresim_yanresimcocuk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.FileField(blank=True, null=True, upload_to='contents', verbose_name='content resmi')),
            ],
        ),
    ]
