# Generated by Django 4.0.6 on 2022-08-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='ContentIndex',
        ),
    ]
