# Generated by Django 4.0.6 on 2022-08-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_kategori_footer_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='kategori',
        ),
    ]
