# Generated by Django 4.0.6 on 2022-08-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0018_footer_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sepetim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(blank=True, null=True, upload_to='cards', verbose_name='card resmi')),
                ('aciklama', models.TextField(max_length=200)),
                ('fiyat', models.CharField(max_length=150)),
                ('adet', models.CharField(max_length=50)),
            ],
        ),
    ]
